<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class UidTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $uidType = [
            [
                "id" => Str::uuid(),
                "siswa_id" => "2d9711a6-b73c-4195-a91e-72c6998461f1",
                "type" => "rfid",
                "value" => "9d2401af"
            ],
            [
                "id" => Str::uuid(),
                "siswa_id" => "122e2b43-1ce6-43f7-850f-8daeda437560",
                "type" => "rfid",
                "value" => "463ee3bc"
            ],
            [
                "id" => Str::uuid(),
                "siswa_id" => "122e2b43-1ce6-43f7-850f-8daeda437560",
                "type" => "face_id",
                "value" => "ew0KICAiaWQiOiAxNzMzMzcxMzI3MzEyLA0KICAibmFtZSI6ICJTYW1zdWwiLA0KICAibGFuZG1hcmtzIjogWw0KICAgIFsNCiAgICAgIHsNCiAgICAgICAgIngiOiAyMjMuNjY5MDE4NTkyMDQ4MTYsDQogICAgICAgICJ5IjogMjYzLjU2ODY3MjM5ODg2MzMNCiAgICAgIH0sDQogICAgICB7DQogICAgICAgICJ4IjogMjI1Ljk0NDE5NTY5MDg1ODgzLA0KICAgICAgICAieSI6IDI4OS4xMTM2MDQ4MjM4ODU0NQ0KICAgICAgfSwNCiAgICAgIHsNCiAgICAgICAgIngiOiAyMzAuNDg4NjAyNDAyOTE0MDQsDQogICAgICAgICJ5IjogMzEzLjI2OTAxMTQxODE2MTkNCiAgICAgIH0sDQogICAgICB7DQogICAgICAgICJ4IjogMjM0Ljk5MzYwMjI0OTEzNDA2LA0KICAgICAgICAieSI6IDMzNC4yMjU4MjIxMzA5NzYyDQogICAgICB9LA0KICAgICAgew0KICAgICAgICAieCI6IDI0Mi41OTMzMTE4MDQ2NDA3NiwNCiAgICAgICAgInkiOiAzNTguNjYxODA0MTE5ODgzMQ0KICAgICAgfSwNCiAgICAgIHsNCiAgICAgICAgIngiOiAyNTUuMjIyNTM1MjcwNTYwMjYsDQogICAgICAgICJ5IjogMzc3LjU0MzYzMjkwNDgyNTcNCiAgICAgIH0sDQogICAgICB7DQogICAgICAgICJ4IjogMjY5Ljg3Mjc5Mjc5ODM4ODQ1LA0KICAgICAgICAieSI6IDM5MS4xNDM3MTA3NzIzMzM2Mw0KICAgICAgfSwNCiAgICAgIHsNCiAgICAgICAgIngiOiAyODguNjk3MTA4ODgyNzczMzYsDQogICAgICAgICJ5IjogNDA0LjY0Mjg3ODY5MTQ5MjU3DQogICAgICB9LA0KICAgICAgew0KICAgICAgICAieCI6IDMxNy4yNDc5NzY4ODczMzM4MywNCiAgICAgICAgInkiOiA0MTIuNDk0NzUzNzU4MjQ5OA0KICAgICAgfSwNCiAgICAgIHsNCiAgICAgICAgIngiOiAzNDUuMjkzMTgwMTU1ODYxOCwNCiAgICAgICAgInkiOiA0MDQuNjU0MTU3MzIwNzk1NTUNCiAgICAgIH0sDQogICAgICB7DQogICAgICAgICJ4IjogMzYyLjc2Mjk2OTQyMjQ0ODEsDQogICAgICAgICJ5IjogMzkyLjMxMjE3OTM2Njg4NDcNCiAgICAgIH0sDQogICAgICB7DQogICAgICAgICJ4IjogMzc2Ljc3ODk2NzM2ODcxMDUsDQogICAgICAgICJ5IjogMzgwLjEwNTgzMDgyODQ4Ng0KICAgICAgfSwNCiAgICAgIHsNCiAgICAgICAgIngiOiAzODkuMDU1NzMwMjcxNDQ3MTUsDQogICAgICAgICJ5IjogMzYwLjc2NjcyMzc5MTg5NTQNCiAgICAgIH0sDQogICAgICB7DQogICAgICAgICJ4IjogMzk3LjkyMTkzNDgzMTI1MDE2LA0KICAgICAgICAieSI6IDMzNy4wMDUzNDE1Njk3MTk4DQogICAgICB9LA0KICAgICAgew0KICAgICAgICAieCI6IDQwMS45NjM2ODM1MzM3NzYyNSwNCiAgICAgICAgInkiOiAzMTUuMTMwOTcyNzgyOTA4DQogICAgICB9LA0KICAgICAgew0KICAgICAgICAieCI6IDQwNi42MDY5ODU4NTUyMTAyNywNCiAgICAgICAgInkiOiAyOTEuOTI2MjU4NDg0NjU5Nw0KICAgICAgfSwNCiAgICAgIHsNCiAgICAgICAgIngiOiA0MDguODg0OTU5NjI2MzA1NTQsDQogICAgICAgICJ5IjogMjY2LjczMzYwMTMxMTk3OTgNCiAgICAgIH0sDQogICAgICB7DQogICAgICAgICJ4IjogMjQ0LjI0MzQwNDAwNDA4NTUzLA0KICAgICAgICAieSI6IDI0MS4wMTM2MjkyMzc5NDc5NQ0KICAgICAgfSwNCiAgICAgIHsNCiAgICAgICAgIngiOiAyNTQuNzMxMTk1ODg1MDUwNzcsDQogICAgICAgICJ5IjogMjMwLjk2NTkwNTQyMzEwMjg3DQogICAgICB9LA0KICAgICAgew0KICAgICAgICAieCI6IDI2OS40NDcwNTI4MjQ2MDQ5NSwNCiAgICAgICAgInkiOiAyMjcuNzcyNDMzOTc2NDY5NTMNCiAgICAgIH0sDQogICAgICB7DQogICAgICAgICJ4IjogMjgyLjc0NDIwNzA0MjU2MzQsDQogICAgICAgICJ5IjogMjI4LjcwNzIzMzIxNTUwODk1DQogICAgICB9LA0KICAgICAgew0KICAgICAgICAieCI6IDI5NC44NzA0NTMwNzc2NjI0MywNCiAgICAgICAgInkiOiAyMzIuOTIxMTAyMjY1NjU0MQ0KICAgICAgfSwNCiAgICAgIHsNCiAgICAgICAgIngiOiAzNDQuNzYwODI5ODU0MTE5MjcsDQogICAgICAgICJ5IjogMjMzLjg1ODU3ODIzMDA4MTENCiAgICAgIH0sDQogICAgICB7DQogICAgICAgICJ4IjogMzU2LjQwNDQwMjU0MjIyMiwNCiAgICAgICAgInkiOiAyMzAuMzA2MjY4MDMxNTM1NjQNCiAgICAgIH0sDQogICAgICB7DQogICAgICAgICJ4IjogMzY4LjgyMzY1NTExNjY2NTgsDQogICAgICAgICJ5IjogMjI4LjYwNzE0Njc1MDAzMQ0KICAgICAgfSwNCiAgICAgIHsNCiAgICAgICAgIngiOiAzODMuNjk3MDkwOTExOTcyOTYsDQogICAgICAgICJ5IjogMjMxLjYyODQxNzY5NTY5OTIzDQogICAgICB9LA0KICAgICAgew0KICAgICAgICAieCI6IDM5My4wNjEzOTgyNTU5MzI4LA0KICAgICAgICAieSI6IDI0MS45NTM2MzQxMjMxNDQ2NA0KICAgICAgfSwNCiAgICAgIHsNCiAgICAgICAgIngiOiAzMTkuMzgxNzk0NDQwODU0MDQsDQogICAgICAgICJ5IjogMjY1LjEwNDcyOTQ1Mzg1OTgNCiAgICAgIH0sDQogICAgICB7DQogICAgICAgICJ4IjogMzE5LjI1Mzk3MDM3Mjc4NDYsDQogICAgICAgICJ5IjogMjgxLjU2OTE5NTg0Njg1Mzc1DQogICAgICB9LA0KICAgICAgew0KICAgICAgICAieCI6IDMxOS4zMjQ5NTEzMzg4NzU3NCwNCiAgICAgICAgInkiOiAyOTYuNzQwMDk1NzE0ODY1Mg0KICAgICAgfSwNCiAgICAgIHsNCiAgICAgICAgIngiOiAzMTkuMDAyNzY2MzU4OTYwMSwNCiAgICAgICAgInkiOiAzMTAuODgxNDM3MzQxNTA5MzUNCiAgICAgIH0sDQogICAgICB7DQogICAgICAgICJ4IjogMzAzLjgyNTU4MTc0NzQwMTIsDQogICAgICAgICJ5IjogMzIxLjcwMDgzOTMyMDk1NTc3DQogICAgICB9LA0KICAgICAgew0KICAgICAgICAieCI6IDMxMC4yNjM5NDgzOTg5MzYyNCwNCiAgICAgICAgInkiOiAzMjMuOTQyNDAxOTI1ODU5OTQNCiAgICAgIH0sDQogICAgICB7DQogICAgICAgICJ4IjogMzE4LjMyNzQ4MTk3MzI3ODk2LA0KICAgICAgICAieSI6IDMyNS4zNjEyNzQyODIyNzQ3NA0KICAgICAgfSwNCiAgICAgIHsNCiAgICAgICAgIngiOiAzMjYuNDcxMTAwMDIwNTE2MzYsDQogICAgICAgICJ5IjogMzIzLjI4Mjc0NTA0MzU3Mzg3DQogICAgICB9LA0KICAgICAgew0KICAgICAgICAieCI6IDMzMi44MTkyMDkzMjU0MjEzLA0KICAgICAgICAieSI6IDMyMi40NTQ1MzI0MjQ3NDYwNQ0KICAgICAgfSwNCiAgICAgIHsNCiAgICAgICAgIngiOiAyNjIuNTY3MTYyNjIxMTI5LA0KICAgICAgICAieSI6IDI2Mi41Nzc0OTc4Nzk4MDEzDQogICAgICB9LA0KICAgICAgew0KICAgICAgICAieCI6IDI3MS4xNjgzMzA4MzY0MDM4LA0KICAgICAgICAieSI6IDI1OS4zMjA0MDM4NTQxODk0DQogICAgICB9LA0KICAgICAgew0KICAgICAgICAieCI6IDI4My4wMDY5NjU3NzQ0MDU0NCwNCiAgICAgICAgInkiOiAyNTkuNDkxOTM4NDIyMjYwOA0KICAgICAgfSwNCiAgICAgIHsNCiAgICAgICAgIngiOiAyOTMuMjE0NDgyODMyMDYyNywNCiAgICAgICAgInkiOiAyNjUuMDAxNjEwNTU3Mzc1NDQNCiAgICAgIH0sDQogICAgICB7DQogICAgICAgICJ4IjogMjg0LjI5ODMyMzU1OTg2ODgsDQogICAgICAgICJ5IjogMjY5LjI3NjAzNTY0NjczNDcNCiAgICAgIH0sDQogICAgICB7DQogICAgICAgICJ4IjogMjcxLjU3MzIxMTIxMTA3Mzg0LA0KICAgICAgICAieSI6IDI2Ny45OTYyNTU1NTY4Nzk1Mw0KICAgICAgfSwNCiAgICAgIHsNCiAgICAgICAgIngiOiAzNDMuMTk0NTQwNjA4MDM2OTYsDQogICAgICAgICJ5IjogMjY1LjQ4MzQwMTYzNjQxOTgNCiAgICAgIH0sDQogICAgICB7DQogICAgICAgICJ4IjogMzU0LjMxNTkxNTAzNjMwOTIsDQogICAgICAgICJ5IjogMjU5Ljc0OTY0MTQ1ODMzMDY0DQogICAgICB9LA0KICAgICAgew0KICAgICAgICAieCI6IDM2Ni43OTc0MjY5ODY4MDIwNywNCiAgICAgICAgInkiOiAyNTkuNzQyNTY5NTc1ODQ0Mw0KICAgICAgfSwNCiAgICAgIHsNCiAgICAgICAgIngiOiAzNzQuMDgyODg1MDE1MTE4NTYsDQogICAgICAgICJ5IjogMjY0LjgxMDYyNzUwMDM1MzM1DQogICAgICB9LA0KICAgICAgew0KICAgICAgICAieCI6IDM2NS42NTQ2NjI1OTcyODcxNCwNCiAgICAgICAgInkiOiAyNjkuODU2MzkxMjkwOTYwOA0KICAgICAgfSwNCiAgICAgIHsNCiAgICAgICAgIngiOiAzNTMuMjUyMzM5MzUxMjg0OTUsDQogICAgICAgICJ5IjogMjY4LjU3NTUwNjcyNzAzNzkNCiAgICAgIH0sDQogICAgICB7DQogICAgICAgICJ4IjogMjg3Ljk4NTU0OTM0ODcwMDUsDQogICAgICAgICJ5IjogMzU1LjkwNjE1NDMxNDgxNDENCiAgICAgIH0sDQogICAgICB7DQogICAgICAgICJ4IjogMjk4LjQ3NDk4MzQ3MTczOTczLA0KICAgICAgICAieSI6IDM0OC45OTAwNTQ2NDcyNjQ5Nw0KICAgICAgfSwNCiAgICAgIHsNCiAgICAgICAgIngiOiAzMTEuMjE5ODM3NDQ1MTI4NCwNCiAgICAgICAgInkiOiAzNDQuMDIyODQ0OTUwNDk1MjYNCiAgICAgIH0sDQogICAgICB7DQogICAgICAgICJ4IjogMzE3Ljk3Mzc1NzYxMjgxMjk2LA0KICAgICAgICAieSI6IDM0NS4zNzc3NzQ3NTUyOTcyDQogICAgICB9LA0KICAgICAgew0KICAgICAgICAieCI6IDMyNC40NTg1OTMxMTgyOTg1LA0KICAgICAgICAieSI6IDM0My40NDc2MzQ4NTYwNDMzNQ0KICAgICAgfSwNCiAgICAgIHsNCiAgICAgICAgIngiOiAzMzcuMjU5MjIwODI2NzMzNTUsDQogICAgICAgICJ5IjogMzQ5Ljk1MjgwNTIwMTM0OTc1DQogICAgICB9LA0KICAgICAgew0KICAgICAgICAieCI6IDM0Ny42NTQ0MjU2Njg4MjQxNiwNCiAgICAgICAgInkiOiAzNTYuNjQ0MDA3OTYxMDkyNQ0KICAgICAgfSwNCiAgICAgIHsNCiAgICAgICAgIngiOiAzMzYuODkxMDExNDA1MDk4OSwNCiAgICAgICAgInkiOiAzNjQuMjg2NjU2NjU3OTkxOQ0KICAgICAgfSwNCiAgICAgIHsNCiAgICAgICAgIngiOiAzMjcuOTkyMTQyNTQ2Mjg0NjQsDQogICAgICAgICJ5IjogMzY5LjI1NzQzOTY1MzIxNTkNCiAgICAgIH0sDQogICAgICB7DQogICAgICAgICJ4IjogMzE3LjQ2NDk4ODkzNTEwMTUsDQogICAgICAgICJ5IjogMzcwLjcyNDI1OTE3Nzk4MDkNCiAgICAgIH0sDQogICAgICB7DQogICAgICAgICJ4IjogMzA4LjAzNTA2MTM0NzU5MjMsDQogICAgICAgICJ5IjogMzY5LjM4MDIzMTE4MTkxNzcNCiAgICAgIH0sDQogICAgICB7DQogICAgICAgICJ4IjogMjk4LjQ0NjIyMTY2NzYzNTksDQogICAgICAgICJ5IjogMzY1LjE1MzkyODY3NzM3ODINCiAgICAgIH0sDQogICAgICB7DQogICAgICAgICJ4IjogMjg5LjkzMTUyNjM1MTA4Mjc3LA0KICAgICAgICAieSI6IDM1Ni4wNTQ0OTE2NzkwMTA5DQogICAgICB9LA0KICAgICAgew0KICAgICAgICAieCI6IDMwOC4zMzUyMjcwOTAyMjgwNSwNCiAgICAgICAgInkiOiAzNTMuMDQ5MDM1ODI3NDU2DQogICAgICB9LA0KICAgICAgew0KICAgICAgICAieCI6IDMxNy44NDI5MDU5ODY0MTY4LA0KICAgICAgICAieSI6IDM1Mi43ODMwMTM1MDI4OTM5NA0KICAgICAgfSwNCiAgICAgIHsNCiAgICAgICAgIngiOiAzMjYuMjgwMDQ0NDI0NjQxNiwNCiAgICAgICAgInkiOiAzNTMuNTI3MDAwMjI4NzAxMQ0KICAgICAgfSwNCiAgICAgIHsNCiAgICAgICAgIngiOiAzNDQuNjYzMTAwODI2ODQ4LA0KICAgICAgICAieSI6IDM1NS45OTk5NTY2NDc2OTIyDQogICAgICB9LA0KICAgICAgew0KICAgICAgICAieCI6IDMyNi45NjE1MDg5MTc5MTYyNiwNCiAgICAgICAgInkiOiAzNTcuOTU1MzQzNTI0NzUyMTUNCiAgICAgIH0sDQogICAgICB7DQogICAgICAgICJ4IjogMzE4LjE0MDQ2Nzc1MTEzMzksDQogICAgICAgICJ5IjogMzU4LjY3NzE4ODc5Mzk1NTM0DQogICAgICB9LA0KICAgICAgew0KICAgICAgICAieCI6IDMwOS4xODUzNTk5MTMyMTg0NiwNCiAgICAgICAgInkiOiAzNTguMTQ5NDQ1MDk2Nzg4OQ0KICAgICAgfQ0KICAgIF0sDQogICAgWw0KICAgICAgew0KICAgICAgICAieCI6IDIyOC41NTUxNjUwMjA3ODU1MiwNCiAgICAgICAgInkiOiAyNjMuODY2NTE4MDA3NTAyMjQNCiAgICAgIH0sDQogICAgICB7DQogICAgICAgICJ4IjogMjMwLjc4NDU4MDI0Mzc4Nzk2LA0KICAgICAgICAieSI6IDI4OS4xMzUxODM1NTk2NDE1DQogICAgICB9LA0KICAgICAgew0KICAgICAgICAieCI6IDIzNS4xNTE1OTg1ODU4MDYwOCwNCiAgICAgICAgInkiOiAzMTMuMzMzMDg1NDk0MDI2OA0KICAgICAgfSwNCiAgICAgIHsNCiAgICAgICAgIngiOiAyMzkuNTU5ODYxNjI4Mzc1MjQsDQogICAgICAgICJ5IjogMzM0LjYzNDk3MDc0MTI1NzM1DQogICAgICB9LA0KICAgICAgew0KICAgICAgICAieCI6IDI0Ni45MzQxMzc1NjYwNTE2NywNCiAgICAgICAgInkiOiAzNTguNzc2ODM5MDk0MTQ3MzYNCiAgICAgIH0sDQogICAgICB7DQogICAgICAgICJ4IjogMjU5LjIyMjY3NzM3ODAyMDUsDQogICAgICAgICJ5IjogMzc3LjE0NjU2Mjk1MDU5NjUNCiAgICAgIH0sDQogICAgICB7DQogICAgICAgICJ4IjogMjc0LjIxNzExNzMzNzU0NjU0LA0KICAgICAgICAieSI6IDM4OS44MjA4MDE2MzIzODk3DQogICAgICB9LA0KICAgICAgew0KICAgICAgICAieCI6IDI5My40ODk5NDUzMjA0NDkwNywNCiAgICAgICAgInkiOiA0MDIuMDYxMDIxOTQwNjkzNTQNCiAgICAgIH0sDQogICAgICB7DQogICAgICAgICJ4IjogMzIxLjkwMTM1NjM5NzIzMzIsDQogICAgICAgICJ5IjogNDA5LjM2MTM0MjIwODM3MDg0DQogICAgICB9LA0KICAgICAgew0KICAgICAgICAieCI6IDM0OS4zMjM3OTI0NTU3NTQ0NywNCiAgICAgICAgInkiOiA0MDIuMjQwODY3NjMxNDIwNzcNCiAgICAgIH0sDQogICAgICB7DQogICAgICAgICJ4IjogMzY2LjAzNjU4MzI0Mjk3NDUsDQogICAgICAgICJ5IjogMzkwLjk3ODY2MjM4ODMxMDENCiAgICAgIH0sDQogICAgICB7DQogICAgICAgICJ4IjogMzc5LjQyNjU4NDU5OTU3NjIsDQogICAgICAgICJ5IjogMzc5LjU2MDc0MjA5Njg4NjMNCiAgICAgIH0sDQogICAgICB7DQogICAgICAgICJ4IjogMzkxLjAyMTA4MjIyMDYzNTYsDQogICAgICAgICJ5IjogMzYwLjg3ODMzMjI3Mzk0NTUNCiAgICAgIH0sDQogICAgICB7DQogICAgICAgICJ4IjogMzk5LjkyNDM5Mjc1Nzk3Mzg2LA0KICAgICAgICAieSI6IDMzNy41NjE1MTkxNjI2NDAyNQ0KICAgICAgfSwNCiAgICAgIHsNCiAgICAgICAgIngiOiA0MDQuMjQwNDU5NDQwMzEyNiwNCiAgICAgICAgInkiOiAzMTUuODcwNzgyMDA0NTgwMg0KICAgICAgfSwNCiAgICAgIHsNCiAgICAgICAgIngiOiA0MDguOTIzNzAyNzE1MDAxMywNCiAgICAgICAgInkiOiAyOTMuMDkwNTM5MjkzMjc0NTYNCiAgICAgIH0sDQogICAgICB7DQogICAgICAgICJ4IjogNDEwLjk5Mzk0NjA3MzYxMzM2LA0KICAgICAgICAieSI6IDI2OC40OTMwODQ5MjQyMDY0DQogICAgICB9LA0KICAgICAgew0KICAgICAgICAieCI6IDI0OS4zMjYzNDgxNTM5MTA4MywNCiAgICAgICAgInkiOiAyMzguOTk3ODkxODU5OTkzNjINCiAgICAgIH0sDQogICAgICB7DQogICAgICAgICJ4IjogMjYwLjEzMjU2MDI1MTMxNzIsDQogICAgICAgICJ5IjogMjI4LjY4OTk0OTA4MjEyMTUzDQogICAgICB9LA0KICAgICAgew0KICAgICAgICAieCI6IDI3NS4yMDM0OTIzNDE1OTk2NiwNCiAgICAgICAgInkiOiAyMjUuNDEzMDM2OTk2NDA5NTcNCiAgICAgIH0sDQogICAgICB7DQogICAgICAgICJ4IjogMjg4LjczMTY0NjM4Njk0MzA1LA0KICAgICAgICAieSI6IDIyNi4zOTkzNDMzNjU3MTQyMw0KICAgICAgfSwNCiAgICAgIHsNCiAgICAgICAgIngiOiAzMDEuMTIx..."
            ],
            [
                "id" => Str::uuid(),
                "siswa_id" => "f5497890-c026-4541-9ba0-404f130f6b19",
                "type" => "rfid",
                "value" => "0ba8ab3b"
            ],
            [
                "id" => Str::uuid(),
                "siswa_id" => "caa651d7-c1c4-462d-b0e0-361d024ed048",
                "type" => "rfid",
                "value" => "f22902af"
            ],
            [
                "id" => Str::uuid(),
                "siswa_id" => "1557a961-368a-47b3-8db9-472d4d49e6a6",
                "type" => "rfid",
                "value" => "f38601af"
            ],
            [
                "id" => Str::uuid(),
                "siswa_id" => "a8d4eaa3-333e-426b-8f52-95ab30edbdd1",
                "type" => "rfid",
                "value" => "93f22334"
            ],
            [
                "id" => Str::uuid(),
                "siswa_id" => "3ae5cca1-2b7f-44ff-a755-182b79112950",
                "type" => "rfid",
                "value" => "aa1cf481"
            ],
            [
                "id" => Str::uuid(),
                "siswa_id" => "bb0f12c8-fc4b-466d-946a-7a5c2b4c9c1c",
                "type" => "rfid",
                "value" => "6a790281"
            ],
            [
                "id" => Str::uuid(),
                "siswa_id" => "8e57e964-0ba9-4f9b-bf7c-c501fc3e54cc",
                "type" => "rfid",
                "value" => "3a9fcb80"
            ],
            [
                "id" => Str::uuid(),
                "siswa_id" => "f66a8dd7-a6a9-41d7-94ca-9c57bb39b09f",
                "type" => "rfid",
                "value" => "aa53d80"
            ],
            [
                "id" => Str::uuid(),
                "siswa_id" => "41a8c545-06bc-4723-bdb5-9de808a820f3",
                "type" => "rfid",
                "value" => "53bbc00d"
            ],
            [
                "id" => Str::uuid(),
                "siswa_id" => "eca61132-9eeb-4c93-93c0-67f9c1ac4c55",
                "type" => "rfid",
                "value" => "b3182e14"
            ],
            [
                "id" => Str::uuid(),
                "siswa_id" => "11791dd5-a02a-4a84-9aaa-a0fa4817d907",
                "type" => "rfid",
                "value" => "33cf9235"
            ],
            [
                "id" => Str::uuid(),
                "siswa_id" => "a323d7e4-19ab-4523-8755-bc4bc6b6ada8",
                "type" => "rfid",
                "value" => "334cfd13"
            ],
            [
                "id" => Str::uuid(),
                "siswa_id" => "dd2911d5-3699-4f77-9f27-248a2cea81ad",
                "type" => "rfid",
                "value" => "83f5650f"
            ],
            [
                "id" => Str::uuid(),
                "siswa_id" => "4d83fc13-b6c4-4bd8-8779-fe815ca21e3b",
                "type" => "rfid",
                "value" => "236a3434"
            ],
            [
                "id" => Str::uuid(),
                "siswa_id" => "9d82f2cc-ae4b-46ba-9130-71abad68c8f8",
                "type" => "rfid",
                "value" => "713tsb78b4"
            ],
            [
                "id" => Str::uuid(),
                "siswa_id" => "9d82f342-f7cd-4127-8c16-a9e08ececc82",
                "type" => "rfid",
                "value" => "q36712yshu3"
            ],
            [
                "id" => Str::uuid(),
                "siswa_id" => "9d82f36e-678e-4e63-807f-514fd8b385bf",
                "type" => "rfid",
                "value" => "n4278cryn7"
            ],
            [
                "id" => Str::uuid(),
                "siswa_id" => "9d82f3c9-bc75-4f67-a431-34d772754336",
                "type" => "rfid",
                "value" => "xrr473jd"
            ]
        ];

        DB::table('uid_types')->insert($uidType);
    }
}
